services:
  nofx:
    image: ghcr.io/34892002/nofx-build/nofx-backend:dev   # <-- 后端镜像（dev 分支构建）
    container_name: nofx
    restart: unless-stopped
    ports:
      - "${NOFX_BACKEND_PORT:-8080}:8080"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./config.db:/app/config.db
      - ./beta_codes.txt:/app/beta_codes.txt:ro
      - ./decision_logs:/app/decision_logs
      - ./prompts:/app/prompts
      # 运行时加密所需的 RSA 密钥目录（包含 rsa_key 与 rsa_key.pub）
      # 生成密钥   ./scripts/setup_encryption.sh
      # https://github.com/NoFxAiOS/nofx/blob/dev/scripts/ENCRYPTION_README.md
      - ./secrets:/app/secrets:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${NOFX_TIMEZONE:-Asia/Shanghai}
      - AI_MAX_TOKENS=${AI_MAX_TOKENS:-4000}
      # 必需：数据库加密密钥（32 字节 Base64 的 AES-256-GCM）
      # 使用 OpenSSL 生成密钥：openssl rand -base64 32
      - DATA_ENCRYPTION_KEY=${DATA_ENCRYPTION_KEY}
      # 使用 OpenSSL 生成JWT认证密钥：openssl rand -base64 64
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - nofx-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nofx-frontend:
    image: ghcr.io/34892002/nofx-build/nofx-frontend:dev  # <-- 前端镜像（dev 分支构建）
    container_name: nofx-frontend
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "${NOFX_FRONTEND_PORT:-3000}:80"
    networks:
      - nofx-network
    depends_on:
      - nofx
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  nofx-network:
    driver: bridge
    
