name: Build and Push via Reusable CI

on:
  push:
    branches: [main, dev]
    tags: ['v*']
  workflow_dispatch:

# 这里的权限会应用到可复用工作流中使用的 GITHUB_TOKEN
permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: your-org/reusable-ci/.github/workflows/docker-build.yml@main
    with:
      create_latest: true
      registry_ghcr: ghcr.io
    # 选一种方式传递密钥：
    # 方案 A：全部继承
    # secrets: inherit
    # 方案 B：点对点映射（更可控）
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}