name: Build and Push via Reusable CI

on:
  push:
    branches: [main, dev]
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: your-org/nofx-build/.github/workflows/docker-build-reusable.yml@main
    with:
      create_latest: true
      registry_ghcr: ghcr.io
      # 如果不想 Fork 上游，直接指定要构建的仓库与分支/标签：
      checkout_repository: NoFxAiOS/nofx
      checkout_ref: main
    # 选择其一：
    # secrets: inherit
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}